{% set name = "stevedore" %}
{% set version = "3.4.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "59b58edb7f57b11897f150475e7bc0c39c5381f0b8e3fa9f5c20ce6c89ec4aa1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - pbr !=2.1.0,>=2.0.0

  run:
    - python
    - pbr !=2.1.0,>=2.0.0
    - importlib_metadata >=1.7.0  # [py<38]

test:
  imports:
    - stevedore
    - stevedore.named
    - stevedore.driver
    - stevedore.hook
    - stevedore.extension
    - stevedore.enabled
    - stevedore.dispatch
    - stevedore.tests
    - stevedore._cache

about:
  home: http://docs.openstack.org/developer/stevedore/
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Manage dynamic plugins for Python applications
  doc_url: http://docs.openstack.org/developer/stevedore/
  dev_url: https://git.openstack.org/cgit/openstack/stevedore

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
    - tschoonj
