travis:
  secure:
    BINSTAR_TOKEN: NPKphJ1+ULAfYW2J+iDQ1X0vYXe8hvPaT9Obyctg6wyGLCTxCCsvHzF6oprx2bjl7i4dRCyIZQT/5/dx/6ZfZsnebqqI6JznyzT2hBvC6I2ceMCURJnUasXJH+FCZ3z3++aZeIpZo4DbXxXbsu8pOnyTR4iRCgbhTgzscYmRIy3ov8IG57auCWsn2BtM2syU+6QyWbLomVOH29nk4cVUhNICNigg9ZnXZlzt8KbQjoHZW9MfEDObDOhGtW4im4TZSTbEooo3DWTiIS1NkS9OBLRuylo69TufiCLhaUNFADP58FHVlg9h9OWXlVguKqnuGvC46lVCseicgV8supLNccjAXcJ7eO/8VfTYhL24Cl8R1TnPWu5Oc948eQoaXpVitjjC5e3Ru7wQqlg7/+T3UmWs22o7f598nqS/ux2tzxtvg+22mPlx1rfFk32YKQN9BEXlka/6B1Lqwvra4v5fBC3vNy7fOwQ/nh8mgg3FDI2fgjNU4cna/7It2hcOGx+Xj6wG5jWFGBDcU8+a56yypaDhCv6qxPiUQkHmlvzkDZYG+/4hPRJjJws0/o8tjAAfGCdtHZEFOb7oFXsrCZ26EpJNU1Ald1SXvYqEorAKARCrZWz88qdYELEemAhek8pcJhfzpqIOeSCJFGOLwGTe4Vy5HSkxERpH91Y6daRF5RA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
