travis:
  secure:
    BINSTAR_TOKEN: QdDhs8gOj05Jy57Qc0esvyl+mGMKawwfY/3OpW3LgDTSjUYBkp/NIZoWyh9tNEfVLpQ0jvGaEskpnrexti0tpKMOa0s/GJiOi+EAE0D4haT9Vk8lpR4FB8VHUBtZ7G8pOwk2o6a5tfXStLWXmJu0O1FlSPff5oNf5RbNXrgbCBHCBx5oJx5tb2CMChI70uQ+0gd7nVj9azXrlOq55cvJbfIl+3gLFkW7ZVTTlYHsl9F721r0/ZVsWlSwXZFxZF/qfPdSuvoYTmXn1zYwbZc+LF+NLpBz6TvzZUjre0LS0I4SVWjI7ANZAhCRsHYx9O+ff7pP0uPx1mOAoywSkTwHHISBbRKp3SFUH339JSpqu4+Oq5svM8AG4Ls/Yq+3yIRTWTcgn10Y9u0yEW0PzshYGlGznCzfTwRm6/eRiKwb0JTfF68iorPmBGfzRYOiM7+Y+6f9JYa7qnvEmzYMKV4SKnDrtBo3Jz1t0DTQk903m7deoScFltadTga0il2QbFmwgMrnlanrdE5BuBAnys8DbrgqfNsU59Qs6rsQ+yqCPbjaYC32V7/SbdLurnLwm8lh1R9os9c4OL2R6771Ek0KATWCRm86djf0VtkaQDQKJ2LW3E1vX4+H7umn6j2TA/1M4C1PZfH/yEHtAgvMNzLFqjUWlvBNCWMsHJptYgGB4Ig=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
